/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;
import clases.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodrigo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Control de ingreso");
        ListaUsuarios.levantarObjetoEntero();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuExportar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenuItem();
        mnuSobreMi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Acceso"
            }
        ));
        jScrollPane1.setViewportView(tblRegistro);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Registro de entradas");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        mnuExportar.setText("Export");
        mnuExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExportarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExportar);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        mnuAyuda.setText("Sobre mi...");
        mnuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAyuda);

        mnuSobreMi.setText("Ayuda");
        mnuSobreMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreMiActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSobreMi);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Main().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mnuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Programa creado por Rodrigo Toledo.", "Sobre mi...", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAyudaActionPerformed

    private void mnuSobreMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreMiActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Tabla con un registro de todos los datos de los usuarios,\n"
                + "incluyendo su ultimo ingreso.", "Ayuda", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuSobreMiActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExportarActionPerformed
        // TODO add your handling code here:
        ExportViewer q = new ExportViewer();
        q.setVisible(true);
    }//GEN-LAST:event_mnuExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuAyuda;
    private javax.swing.JMenuItem mnuExportar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuSobreMi;
    private javax.swing.JTable tblRegistro;
    // End of variables declaration//GEN-END:variables
//Modelo de tabla personalizada
    private void refreshTable() {
        
        //Levantamos los datos a cargar
        Usuario[] listado = ListaUsuarios.getLista();
        
        //Creamos el modelo de datos de la tabla.
        DefaultTableModel model = new DefaultTableModel() {
            /*Edito un método de la clase "DefaultTableModel" y cada vez que 
             se renderiza un celda, cuando se pregunta si es editable le digo que no.
             Lo explico mejor en clase;
             */
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column==5){
                    return true;
                }
                return false;
            }
            Object[][] data = {};
            //
            // This method is used by the JTable to define the default
            // renderer or editor for each cell. For example if you have
            // a boolean data it will be rendered as a check box. A
            // number value is right aligned.
            
//            @Override
//            public Class<?> getColumnClass(int columnIndex) {
//            return getValueAt(0, columnIndex).getClass();
//            
//        }

        };

        model.addColumn("Nombre");
        model.addColumn("Dni");
        model.addColumn("Telefono");
        model.addColumn("Mail");
        model.addColumn("Ultimo ingreso");

        for (int i = 0; i < listado.length; i++) {
            if (listado[i] != null) {
                Object[] fila = new Object[5];
                fila[0] = listado[i].getNombre();
                fila[1] = "" + listado[i].getDni();
                fila[2] = "" + listado[i].getTel();
                fila[3] = listado[i].getMail();
                fila[4] = listado[i].gethLlegada();                
                model.addRow(fila);
            }
        }
        tblRegistro.setModel(model);
    }
}
